// deploy-dev.ts — 把本仓库构建出来的记忆插件部署为一个新的开发修订版并热生效。
//
// 为什么需要它（M-1 spike 实测）：DSH 不会热重载第三方插件的代码 —— Node 的 ESM
// 缓存按真实路径命中，DSH 也不为第三方模块做 cache-bust。实测结论：
//   · 改文件内容（同路径）        → 永远拿到旧模块
//   · 改已有条目的 name（换路径）  → 只更新元数据，运行中的 fiber 不变
//   · 新增条目 id + 新物理路径     → 立即生效 ✅
//   · 改条目 config               → 生效
// 所以每次迭代 = 复制到 dev/rev<N>/ + 在 profile patch 里新增一条 memory-dev<N>，
// 并把之前的修订版标记为 disabled。配置层的变化是即时的，无需重启 DSH。
//
// 用法（Node 原生剥离类型，无需构建）：
//   node tools/deploy-dev.ts [--lib-dir <path>] [--domain <name>] [--set "k=v;k=v"] [--simulate-capture-error]
//
// 注意：源码是 TypeScript，必须**先构建**（pnpm build），本脚本部署的是编译产物 lib/。

import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

interface Options {
  libDir: string
  domain: string
  simulateCaptureError: boolean
  set: string
}

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')

function parseArgs(argv: string[]): Options {
  const options: Options = {
    libDir: join(repoRoot, 'lib'),
    domain: 'dsh_memory_dev',
    simulateCaptureError: false,
    set: '',
  }
  for (let index = 0; index < argv.length; index += 1) {
    const arg = argv[index]
    if (arg === '--lib-dir') options.libDir = resolve(argv[++index] ?? '')
    else if (arg === '--domain') options.domain = argv[++index] ?? options.domain
    else if (arg === '--set') options.set = argv[++index] ?? ''
    else if (arg === '--simulate-capture-error') options.simulateCaptureError = true
    else if (arg === '--help' || arg === '-h') {
      console.log('用法：node tools/deploy-dev.ts [--lib-dir <path>] [--domain <name>] [--set "k=v;k=v"] [--simulate-capture-error]')
      process.exit(0)
    } else {
      console.warn(`忽略未知参数: ${arg}`)
    }
  }
  return options
}

/** 递归复制一个目录（`cp -r src/* dest/` 的等价物，不引入额外依赖）。 */
function copyDirContents(source: string, target: string): void {
  mkdirSync(target, { recursive: true })
  for (const entry of readdirSync(source)) {
    const from = join(source, entry)
    const to = join(target, entry)
    if (statSync(from).isDirectory()) copyDirContents(from, to)
    else copyFileSync(from, to)
  }
}

function main(): void {
  const options = parseArgs(process.argv.slice(2))

  const profileDir = process.env.DSH_PROFILE_DIR
  if (!profileDir) throw new Error('DSH_PROFILE_DIR 不可用：请在 DSH 的 shell 中运行')
  const patchPath = join(profileDir, 'cordis.patch.yml')
  if (!existsSync(patchPath)) throw new Error(`找不到 profile patch: ${patchPath}`)
  if (!existsSync(join(options.libDir, 'index.js'))) {
    throw new Error(`找不到编译产物: ${join(options.libDir, 'index.js')} —— 请先在仓库根目录运行 pnpm build`)
  }

  const devRoot = join(profileDir, 'dev')
  mkdirSync(devRoot, { recursive: true })

  // 下一个修订号：必须**全局单调、永不重用**。
  // 原因（踩过）：Node 的 ESM 缓存按解析后的真实路径命中，DSH 不为第三方模块做 cache-bust。
  // 一旦复用曾经用过的路径，拿回的会是当时缓存里的**旧模块**（实测：dev/rev1、dev/rev2 曾装过
  // M-1 spike，重新从 1 开始编号后加载到的是 spike 代码，而不是新代码）。
  const counterPath = join(profileDir, '.dsh-memory-dev-rev')
  const rawCounter = existsSync(counterPath) ? readFileSync(counterPath, 'utf8').trim() : ''
  const lastRev = /^\d+$/u.test(rawCounter) ? Number(rawCounter) : 0
  let rev = lastRev + 1
  while (existsSync(join(devRoot, `rev${rev}`))) rev += 1
  writeFileSync(counterPath, String(rev), 'utf8')

  const revDir = join(devRoot, `rev${rev}`)
  mkdirSync(revDir, { recursive: true })
  copyDirContents(options.libDir, revDir)
  // 必须同时有非空 name 与 version：plugin-package-inventory 会读每个活动条目的清单，
  // 缺字段会让该 profile 的每个模型请求都以 REQUEST_EXTENSION 失败（UI 上看不出原因）。
  writeFileSync(
    join(revDir, 'package.json'),
    `{ "name": "dsh-memory-dev", "version": "0.${rev}.0", "private": true, "type": "module" }\n`,
    'utf8',
  )

  const entryId = `memory-dev${rev}`
  const reportDir = join(repoRoot, 'reports')
  mkdirSync(reportDir, { recursive: true })
  const reportPath = join(reportDir, `rev${rev}.json`).replace(/\\/gu, '/')

  // 收集此前生成过的条目 id（用于停用）
  let patchText = readFileSync(patchPath, 'utf8')
  const previousIds = [...patchText.matchAll(/^\s*- id: (memory-dev\d*)\s*$/gmu)].map((match) => match[1] ?? '')
  const uniquePreviousIds = [...new Set(previousIds)].sort()

  const block: string[] = ['# >>> dsh-memory dev (auto-generated by tools/deploy-dev.ts) — 不要手工编辑这一段']
  for (const id of uniquePreviousIds) {
    if (id !== entryId) block.push(`- id: ${id}\n  disabled: true`)
  }

  const configLines: string[] = [
    `        revision: ${rev}`,
    `        reportPath: '${reportPath}'`,
    `        domainName: ${options.domain}`,
    '        seed: true',
  ]
  if (options.simulateCaptureError) {
    configLines.push('        # 故障注入：捕获链路故意抛错，验证异常不影响对话（设计稿 §11.2 用例 7）')
    configLines.push('        simulateCaptureError: true')
  }
  for (const item of options.set.split(';').filter((part) => part.trim().length > 0)) {
    const separator = item.indexOf('=')
    if (separator > 0) {
      configLines.push(`        ${item.slice(0, separator).trim()}: ${item.slice(separator + 1).trim()}`)
    } else {
      console.warn(`忽略无法解析的 --set 项: ${item}（应为 key=value，多项用分号分隔）`)
    }
  }

  block.push('- insert:')
  block.push(`    - id: ${entryId}`)
  block.push(`      name: './dev/rev${rev}/index.js'`)
  block.push('      config:')
  block.push(...configLines)
  block.push('# <<< dsh-memory dev')

  const marker = /# >>> dsh-memory dev[\s\S]*?# <<< dsh-memory dev\r?\n?/u
  const newBlock = `${block.join('\n')}\n`
  if (marker.test(patchText)) {
    patchText = patchText.replace(marker, newBlock)
  } else {
    if (!patchText.endsWith('\n')) patchText += '\n'
    patchText += newBlock
  }
  writeFileSync(patchPath, patchText, 'utf8')

  console.log(`deployed rev${rev}`)
  console.log(`  entry : ${entryId}`)
  console.log(`  module: ./dev/rev${rev}/index.js`)
  console.log(`  report: ${reportPath}`)
  console.log(`  disabled previous: ${uniquePreviousIds.join(', ')}`)
}

main()
