# deploy-dev.ps1 — 把工作区里的记忆插件源码部署为一个新的开发修订版并热生效。
#
# 为什么需要它（M-1 spike 实测）：DSH 不会热重载第三方插件的代码 —— Node 的 ESM
# 缓存按真实路径命中，DSH 也不为第三方模块做 cache-bust。实测结论：
#   · 改文件内容（同路径）        → 永远拿到旧模块
#   · 改已有条目的 name（换路径）  → 只更新元数据，运行中的 fiber 不变
#   · 新增条目 id + 新物理路径     → 立即生效 ✅
#   · 改条目 config               → 生效
# 所以每次迭代 = 复制到 dev/rev<N>/ + 在 profile patch 里新增一条 memory-dev<N>，
# 并把之前的修订版标记为 disabled。配置层的变化是即时的，无需重启 DSH。
#
# 用法：pwsh -File tools\deploy-dev.ps1 [-Source <path>] [-Domain <name>]

param(
  # 默认取本仓库的 src/（相对于脚本位置，不写死任何绝对路径）
  [string]$SrcDir = (Join-Path (Split-Path $PSScriptRoot -Parent) 'src'),
  [string]$Domain = 'dsh_memory_dev',
  [switch]$SimulateCaptureError,
  # 追加配置，形如 -Set "recallMode='dry';maxInjectedTokens=200"（分号分隔；
  # 注意 pwsh -File 不支持哈希表，也不要把多个值用逗号传进来——那会变成一个字符串）
  [string]$Set = ''
)

$ErrorActionPreference = 'Stop'
$profileDir = $env:DSH_PROFILE_DIR
if (-not $profileDir) { throw 'DSH_PROFILE_DIR 不可用：请在 DSH 的 shell 中运行' }
$patchPath = Join-Path $profileDir 'cordis.patch.yml'
if (-not (Test-Path $patchPath)) { throw "找不到 profile patch: $patchPath" }
if (-not (Test-Path (Join-Path $SrcDir 'index.js'))) { throw "找不到插件入口: $SrcDir\index.js" }

$devRoot = Join-Path $profileDir 'dev'
New-Item -ItemType Directory -Force -Path $devRoot | Out-Null

# 下一个修订号：必须**全局单调、永不重用**。
# 原因（踩过）：Node 的 ESM 缓存按解析后的真实路径命中，DSH 不为第三方模块做 cache-bust。
# 一旦复用曾经用过的路径，拿回的会是当时缓存里的**旧模块**（实测：dev/rev1、dev/rev2 曾装过
# M-1 spike，重新从 1 开始编号后加载到的是 spike 代码，而不是新代码）。
$counterPath = Join-Path $profileDir '.dsh-memory-dev-rev'
$lastRev = 0
if (Test-Path $counterPath) {
  $raw = (Get-Content $counterPath -Raw).Trim()
  if ($raw -match '^\d+$') { $lastRev = [int]$raw }
}
$rev = $lastRev + 1
while (Test-Path (Join-Path $devRoot "rev$rev")) { $rev += 1 }
Set-Content $counterPath $rev -Encoding utf8 -NoNewline

$revDir = Join-Path $devRoot "rev$rev"
New-Item -ItemType Directory -Force -Path $revDir | Out-Null
Copy-Item (Join-Path $SrcDir '*') $revDir -Recurse -Force
# 必须同时有非空 name 与 version：plugin-package-inventory 会读每个活动条目的清单，
# 缺字段会让该 profile 的每个模型请求都以 REQUEST_EXTENSION 失败（UI 上看不出原因）。
('{ "name": "dsh-memory-dev", "version": "0.' + $rev + '.0", "private": true, "type": "module" }') |
  Set-Content (Join-Path $revDir 'package.json') -Encoding utf8

$entryId = "memory-dev$rev"
$repoRoot = Split-Path $PSScriptRoot -Parent
$reportDir = Join-Path $repoRoot 'reports'
New-Item -ItemType Directory -Force -Path $reportDir | Out-Null
$reportPath = (Join-Path $reportDir "rev$rev.json") -replace '\\', '/'

# 收集此前生成过的条目 id（用于停用）
$patchText = Get-Content $patchPath -Raw
$previousIds = [regex]::Matches($patchText, '(?m)^\s*- id: (memory-dev\d*)\s*$') |
  ForEach-Object { $_.Groups[1].Value } | Sort-Object -Unique

$block = @()
$block += '# >>> dsh-memory dev (auto-generated by tools/deploy-dev.ps1) — 不要手工编辑这一段'
foreach ($id in $previousIds) {
  if ($id -ne $entryId) { $block += "- id: $id`n  disabled: true" }
}

$configLines = @(
  "        revision: $rev"
  "        reportPath: '$reportPath'"
  "        domainName: $Domain"
  "        seed: true"
)
if ($SimulateCaptureError) {
  $configLines += '        # 故障注入：捕获链路故意抛错，验证异常不影响对话（设计稿 §11.2 用例 7）'
  $configLines += '        simulateCaptureError: true'
}
foreach ($item in ($Set -split ';' | Where-Object { $_.Trim().Length -gt 0 })) {
  $parts = $item -split '=', 2
  if ($parts.Count -eq 2) {
    $configLines += "        $($parts[0].Trim()): $($parts[1].Trim())"
  } else {
    Write-Warning "忽略无法解析的 -Set 项: $item（应为 key=value，多项用分号分隔）"
  }
}

$block += '- insert:'
$block += "    - id: $entryId"
$block += "      name: './dev/rev$rev/index.js'"
$block += '      config:'
$block += $configLines
$block += '# <<< dsh-memory dev'

$marker = '(?s)# >>> dsh-memory dev.*?# <<< dsh-memory dev\r?\n?'
$newBlock = ($block -join "`n") + "`n"
if ($patchText -match $marker) {
  $patchText = [regex]::Replace($patchText, $marker, [System.Text.RegularExpressions.MatchEvaluator]{ param($m) $newBlock })
} else {
  if (-not $patchText.EndsWith("`n")) { $patchText += "`n" }
  $patchText += $newBlock
}
Set-Content $patchPath $patchText -Encoding utf8 -NoNewline

Write-Output "deployed rev$rev"
Write-Output "  entry : $entryId"
Write-Output "  module: ./dev/rev$rev/index.js"
Write-Output "  report: $reportPath"
Write-Output "  disabled previous: $($previousIds -join ', ')"
